version: '3'
services:
  postgres:
    image: postgres:10
    volumes:
      - ./data/postgres:/var/lib/postgresql
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
  sonarqube:
    image: sonarqube:7.9-community
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    volumes:
      - ./start.sh:/opt/sonarqube/start.sh
      - ./sonar-pmd-plugin-3.2.1.jar:/opt/sonarqube/extensions/plugins/sonar-pmd-plugin-3.2.1.jar
    entrypoint: /opt/sonarqube/start.sh
    environment:
      - USER_LOGIN=test
      - USER_NAME=test
      - USER_PASSWORD=password123
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
